version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=key3165880
      - MYSQL_DATABASE=registrohoras
      - MYSQL_USER=jetbill
      - MYSQL_PASSWORD=key3165880
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8090:8090
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
